### PR TITLE
Catch SIGPIPEs to stay alive when the other end disappears

### PR DESCRIPTION
**Pull request by jean-edouard**
OXT-733

Signed-off-by: Jed lejosnej@ainfosec.com

### CODE REVIEW

**Comment by rneilturner** [comment]
I will give this a go and report back.

**Comment by rneilturner** [comment]
Just tested this fix and it looks good! +1

**Comment by rossphilipson** [comment]
Let's fix that in stable-6

**Comment by rossphilipson** [comment]
Got a test and fixed +1 - LGTM too. Merging these soon.

**Pull request merged**
